- name: Check if file already exists for {{ symlink_item }}
  stat: path="{{ user_home }}/.{{ symlink_item }}"
  register: prevfile
  failed_when: False

- name: Backup previous {{ symlink_item }}
  command: mv {{ user_home|quote }}/.{{ symlink_item }} {{ user_home|quote }}/.{{ symlink_item }}.bak
  args:
    creates: "{{ user_home }}/.{{ symlink_item }}.bak"
  when:
    - prevfile.stat.exists
    - not prevfile.stat.islnk

- name: Create a symlink for {{ symlink_item }}
  file:
    src: "{{ dotfiles_path }}/{{ symlink_item }}"
    dest: "{{ user_home }}/.{{ symlink_item }}"
    state: link
